### ISSUE TITLE
oemof groups

### ISSUE THREAD

**Issue by uvchik** [oemof/organisation#11]
At the oemof developer meeting we talked about decision making in oemof.

For some developer it is annoying that they try to integrate the whole group but do not get replies.

Therefore we decided to separate the organisation with two new teams. Please correct me if I report something wrong.

It is not an honour or an award for something to be part of a team. It is just an information for others.

 * The members of the **repository teams** have the right to push into their repository, but have to take care of these repositories, review pull requests, and fix reported bugs. If you do not feel confident you shoud not be part of this team but contribute via pull requests.

* The members of the **developer team** should somehow feel related to the developing process of oemof. Members of these group should know each other a little more than just by their github user name and should know a way to contact them e.g. by e-mail. This group is the owner of the license and the members should be reply to issues regarding the license .

* The members of the **steering committee** should be interested in the whole oemof project. They should take part in discussion regarding the future of oemof (issues, web-conferences, meetings), call of or reply in any way. Members of this group should know each other and new members should be introduced somehow.

We do not want to create hard rules but want to avoid that we wait for the response of somebody who is no longer interested. You can 

**Please unsign if you think, that you are not in the right group**. Or join if you think you should belong to one of these groups. You can also leave and rejoin later. Not being a member of a team does not mean that you are not part of oemof. The oemof community is much bigger and everybody who uses, contributes or supports oemof in any way is part of this community. If you want to stay in contact without getting to much e-mails, just follow the blog on our [website](https://oemof.wordpress.com/).

Any objections :question: 

Do you think there should be a loose group for the community? Proposals are welcome!

**Comment by simnh** [comment]
If you decided this way on the meeting, I am fine with it...

**Comment by uvchik** [comment]
> I think pull requests are a good way for new features or major changes anyway (for all people)

I strongly support that :+1:

**Comment by beritRLI** [comment]
Thank you Uwe for the summary of the team organisation!
I feel good with that and I don't think that we should organise a group for the community - I think that shoul slowly develop itself...

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
Closed in favour of #23.
