### ISSUE TITLE
oemof-website: publications & active projects

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/organisation#13]
Add new/adapt pages on oemof's website:

* Publications
  * Articles
  * Presentations
* Applications
  * Active projects (projects arround oemof by different people/institutions e.g. oemof heat, ...) 
  * Existing publications (reegis, renpassG!S, HESYSOPT, ...)

**Comment by birgits** [comment]
I finally added the open fred project to the [applications page](https://oemof.org/applications/). I also added a sentence to the introduction trying to explain why we differentiate between apps and projects. Feel free to change it if you don't agree or like the project description. @c-moeller you could maybe add oemof heat?

**Comment by ckaldemeyer** [comment]
> I finally added the open fred project to the applications page. I also added a sentence to the introduction trying to explain why we differentiate between apps and projects. Feel free to change it if you don't agree or like the project description. @c-moeller you could maybe add oemof heat?

Thanks for your contribution. One suggestion: I would shorten the name "open_FRED: open feed-in time series based on a Renewable Energy Database" in accordance to the other titles.

**Comment by busiing** [comment]
I feel like there are a lot of closable issues. The tabs were added and now redesigned (Model & Project)
