### ISSUE TITLE
Next user/developer meeting

### ISSUE THREAD

**Issue by uvchik** [oemof/organisation#16]
@oemof/oemof-developer-group 

Where will be the next developer meeting (Magdeburg, Flensburg)?
When will be the next developer meeting (November/December)?
Shall we combine it again with a user meeting?

**Comment by birgits** [comment]
I am not sure if this was discussed at the last oemof webco? I wanted to bring it up again in case we decide to have a combined user and developer meeting in the fall. I think we half decided to have a developer meeting in November/December and another user meeting in spring at the webco in June but @ckaldemeyer wanted to ask his professor if they wanted to host a combined user/developer meeting. Any news?

**Comment by ckaldemeyer** [comment]
> I am not sure if this was discussed at the last oemof webco? I wanted to bring it up again in case we decide to have a combined user and developer meeting in the fall. I think we half decided to have a developer meeting in November/December and another user meeting in spring at the webco in June but @ckaldemeyer wanted to ask his professor if they wanted to host a combined user/developer meeting. Any news?

Not yet because everybody is on holiday!

**Comment by uvchik** [comment]
Could it be a good idea to combine the developer meeting with the last polish on v0.2.0 and release afterwards?

@oemof/oemof-developer-group Who is interested in a developer meeting?

**Comment by c-moeller** [comment]
I'm interested.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group, @wind-python/team 

I talked to some people and found out that there is a general interest to have a developer meeting this winter and maybe a user meeting next spring. I would suggest Flensburg as the place, but we can discuss this.

I would like to call it "oemof organisation meeting" and invite everybody who feels (or wants to feel) involved in coding (network, solph, feedinlib, demandlib, windpowerlib), documentation, public relation, organisation, acquisition of projects or anything else connected to the oemof project.

I think it is important to meet and talk about the project as a whole. Of course we could divide in subgroups for special topics like the release of v0.2.

Please commit yourself with your interests, wishes and possibible contributions.

i created a poll to find a date for the meeting: https://xoyondo.com/dp/Fult8jSYFTMEn40

**Comment by ckaldemeyer** [comment]
> @oemof/oemof-developer-group,
> 
> I talked to some people and found out that there is a general interest to hold a developer meeting this winter and maybe a user meeting next spring. I would suggest Flensburg as the place, but we can discuss this.
> 
> I would like to call it "oemof organisation meeting" and invite everybody who feels (or wants to feel) involved in coding (network, solph, feedinlib, demandlib, windpowerlib), documentation, public relation, organisation, acquisition of projects or anything else connected to the oemof project.

Thanks for creating!

> I think it is important to meet and talk about the project as a whole. Of course we could divide in subgroups for special topics like the release of v0.2.

I think this would be a bit late for `v0.2` and rather for `v0.2.1` !? :-)

**Comment by uvchik** [comment]
Shall we keep the general format of the last meetings? 

If we do so, according to the poll this meeting would be from:

**4th December, 2pm** to **6th December, 2pm**

Any comments?

**Comment by ckaldemeyer** [comment]
> Shall we keep the general format of the last meetings?
> 
> If we do so, according to the poll this meeting would be from:
> 
> 4th December, 2pm to 6th December, 2pm
> 
> Any comments?

Should we reduce it to two days e.g. from the 4th to the 5th? I think it would be sufficient and I am trying to household with my time a bit ;-)

**Comment by uvchik** [comment]
I started an issue (#22)  to collect topics and plan the meeting. Maybe we could decide than but as you are a local participant it shouldn't be difficult for to take part partially.

**Comment by uvchik** [comment]
Closed it favour of #22.
