### ISSUE TITLE
Prepare oemof webinar

### ISSUE THREAD

**Issue by c-moeller** [oemof/organisation#19]
We've got a request from the "Forschungsnetzwerk Systemanalyse (AG 3)" to hold a webinar on oemof in the context of their regular webinar series, see also https://www.forschungsnetzwerke-energie.de/forschungsnetzwerk-systemanalyse/arbeitsgruppen

In our project "oemof_heat" we have a budget for workshops, so I could prepare such a webinar if there are no objections. Any ideas or hints are of course very welcome.

I think @simnh and @ckaldemeyer have already been informed. Could you briefly post if you discuss more than I know... (I know everything I've just posted in this issue :smile:)

**Comment by ckaldemeyer** [comment]
> We've got a request from the "Forschungsnetzwerk Systemanalyse (AG 3)" to hold a webinar on oemof in the context of their regular webinar series, see also https://www.forschungsnetzwerke-energie.de/forschungsnetzwerk-systemanalyse/arbeitsgruppen
> 
> In our project "oemof_heat" we have a budget for workshops, so I could prepare such a webinar if there are no objections. Any ideas or hints are of course very welcome.
> 
> I think @simnh and @ckaldemeyer have already been informed. Could you briefly post if you discuss more than I know... (I know everything I've just posted in this issue )

We left the webroom before the end so there's nothing to add. Feel free to prepare something! :+1:

**Comment by c-moeller** [comment]
To give you an update: the webinar will take place in the end of October / beginning of November. It looks like I'll have 30 min for a presentation and some additional time for questions. I'm going to clarify further details in the next days. If you have something I should consider, please let me know.

**Comment by ckaldemeyer** [comment]
> To give you an update: the webinar will take place in the end of October / beginning of November. It looks like I'll have 30 min for a presentation and some additional time for questions. I'm going to clarify further details in the next days. If you have something I should consider, please let me know.

:+1:

**Comment by c-moeller** [comment]
The webinar takes place on the 10th of January. I will publish an announcement on our news-blog soon. If anyone has any more comments or wishes for the webinar, please contact me.

**Comment by ckaldemeyer** [comment]
> The webinar takes place on the 10th of January. I will publish an announcement on our news-blog soon. If anyone has any more comments or wishes for the webinar, please contact me.

Thanks. Are you going to pre-publish some slides or a structure/ToC?!

**Comment by c-moeller** [comment]
Yes, that's a good idea. I think I will do this in the first week of January. Hope this will be not too late.

**Comment by ckaldemeyer** [comment]
> Yes, that's a good idea. I think I will do this in the first week of January. Hope this will be not too late.

Sounds good. We can also provide old presentations, ...

**Comment by c-moeller** [comment]
For the webinar I have the following rough agenda:
* Introduction of oemof via variety of examples --> for what oemof has been used yet
* How to use
* How to contribute

For the second and third point I have the slides from the openmod workshop which I can easily extend by a contribution part.

For the first part it would be nice if you can send me some old slides which describe your projects in the oemof context if you have some. That would help me a lot and also ensure that I don't forget anyone @oemof/oemof-developer-group Thank you!!

**Comment by simnh** [comment]
Three points: 

I think one slide outlining the central, distinct features of oemof compared to other existing software would be nice before you start with the pratical stuff: 

Combination of: 
- collaborative development (community based) 
- graph based structure 
- high level programming language

Also I think, you should have a look at the paper we have been submitting, which should clearify this one...

Despite the fact most people use solph it shoul be clear that when we say oemof, we actually mean the framework and its associated structures and processes and not the software (or a part of ist, e.g. solph) itself. At least thats what I think :-) 

I will send you some slides via mail!

**Comment by c-moeller** [comment]
I have uploaded the slides here: https://oemof.org/2018/01/10/oemof-webinar-slides-download/
Many thanks for your feedback and support!
