### ISSUE TITLE
oemof @ openmod conference in Munich, October 2017

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/organisation#20]
Who will attend to the [next openmod conference in October](https://wiki.openmod-initiative.org/wiki/Open_Energy_Modelling_Workshop_-_Munich_2017#Day_1:_Optional_Tutorials_.28Wednesday_11_October_2017.29)?

I think it would be nice to provide some hands on tutorials there. Maybe based on the examples of the oemof user meeting or the webinar (#19).

At the moment, I am not sure if I will be able to go there.

**Comment by wolfbunke** [comment]
I am not 100% sure but will try to join in.

**Comment by ckaldemeyer** [comment]
> I am not 100% sure but will try to join in.

In the oemof tuturials?

**Comment by birgits** [comment]
I will be there. Which slot would you see the oemof tutorial in? As far as I saw the energy model slot is again quite short. I'm not sure if that is set in stone though.

**Comment by beritRLI** [comment]
I assign Caro also to this issue, because she is preparing a presentation for the PTJ webinar - that might also fit (with little changes) for the tutorial.

**Comment by ckaldemeyer** [comment]
> I will be there. Which slot would you see the oemof tutorial in? As far as I saw the energy model slot is again quite short. I'm not sure if that is set in stone though.

Oh, I missed that. It looks as if the only thing that's suitable is a presentation within "Energy model introductions" and so no specific workshop.. Thanks for clarifying! If there will be tutorials, we can still offer something.

> I assign Caro also to this issue, because she is preparing a presentation for the PTJ webinar - that might also fit (with little changes) for the tutorial.

:+1:  Or she/we/someone might take mine from the last workshop or @uvchik's from the workshop in Bremen.

**Comment by beritRLI** [comment]
Nothing is in stone! They just took the agenda from last year. We can propose an introduction workshop to oemof lasting longer (if they have enough rooms I think there shouldn't be objections).
At least we should offer that if we can provide it

**Comment by gplssm** [comment]
I'm attending at the next openMod workshop as well. I would be happy if someone else who is more familiar with the details of using oemof could give the workshop, but otherwise I could help out

**Comment by ckaldemeyer** [comment]
> I'm attending at the next openMod workshop as well. I would be happy if someone else who is more familiar with the details of using oemof could give the workshop, but otherwise I could help out

I have decided not to attend because of scarce time in October. Unfortunately..

But other people from Flensburg like @simnh who are familiar with oemof might go there!

**Comment by birgits** [comment]
I will also not attend the next openmod after all but I could help preparing something!
