### ISSUE TITLE
oemof organisation meeting in Flensburg (4.12. - 6.12. 2017)

### ISSUE THREAD

**Issue by uvchik** [oemof/organisation#22]
@oemof/oemof-developer-group According to the typical format of oemof meetings the meeting would start 4.12.2017 about noon and end on 6.12.2017 around noon.

Possible topics could be:
- solph roadmap/release?
- oemof roadmap (Future of feedinlib, demandlib, windpowerlib,...)
- integration of new developers/supporters
- public relations
- acquisition of projects
- who is working on oemof? / who is planing to contribute?
- non-linear formulations
- multi period model (expansion optimization)

- ...

Who will take part (please add your name)
- @uvchik 
- @beritRLI (only 1 day)
- @EdithaK (only 1 day)
- @jnnr 
- @c-moeller
- @pkassing 
- @birgits 
- @SabineHaas 
- @simnh 
- @ckaldemeyer 
- @s3pp ?
- @wolfbunke
- @gnn 
- @mloenneberga
- Tillmann

Please invite people who may be interested in supporting (not only using) oemof and its libraries. I think the meeting could be a good place to integrate new people.

**Comment by EdithaK** [comment]
Knowing that I am not to much into your existing management structure there are some organisational questions (suggestions):

Who is working on oemof in which context (projects/PhDs) and topics?
* Projects, PhDs, developers
* Future Projects, PhDs, participants
* joint acquisition of projects

Would it be helpful if we handle oemof with project management tools /philosophy? 
* How often do we meet / who is organizing this?
* tools requiered? own-cloud ect.
* collection for ideas for acquisition of projects

Responsibilities PR:
* Responsibilitie for maintenance of website
* Are there whishes for the website structure (List of apps / projects) 
* Is there something to consider when talking to others. ... 

Responsibilities for code parts
* Organisation of code documentation

**Comment by EdithaK** [comment]
Are there open task from last user/developer meeting?

**Comment by EdithaK** [comment]
It would be great if we could talk about organisational Tasks at Moday/Tuesday....

**Comment by uvchik** [comment]
I would like to invite everybody, who may be interested in contributing. If there will be enough new people I could make a little workshop. " How to contribute, how works the oemof project, etc."

@oemof/oemof-developer-group Are the any interested people in Flensburg, Berlin or elsewhere, who we could invite. I think a developer meeting could be a good start and a good motivation. It also could reduce barriers/shyness....

**Comment by beritRLI** [comment]
@uvchick I like that idea!
@oemof/oemof-developer-group: I started a wiki with the collection of topics (copied from above) and with the collection of possible working groups - please add your favourite working group subjects (until **8th of November**??!) with a short description and also add your name to those you want to participate in. 
To find the order and timeframes of the topics we have to run an optimisation regarding the participants of the various groups....

**Comment by c-moeller** [comment]
> I started a wiki with the collection of topics

Thank you! @beritRLI 

Here is the link to the wiki:
https://github.com/oemof/organisation/wiki/Organising-developer-meeting-Dec.2017-in-Flensburg

**Comment by beritRLI** [comment]
at the last meeting we decided (?) that we want to add an overview of the projects using/developing oemof on the oemof site.  I think nobody gathered them up to now. If somebody feels responsible tell me, otherwise I would like to take that over.
And I would like you to gather them in the organising wiki in Top 1 (because I think it is a good start for the discussion of that topic). 
@simnh @ckaldemeyer @wolfbunke could you fill that from Flensburg side?

**Comment by ckaldemeyer** [comment]
> at the last meeting we decided (?) that we want to add an overview of the projects using/developing oemof on the oemof site. I think nobody gathered them up to now. If somebody feels responsible tell me, otherwise I would like to take that over.
> And I would like you to gather them in the organising wiki in Top 1 (because I think it is a good start for the discussion of that topic).
> @simnh @ckaldemeyer @wolfbunke could you fill that from Flensburg side?

Go ahead! ;-)

**Comment by beritRLI** [comment]
Dear oemof developers. At the last openmod meeting Kais from Munich headed the breakout group on "joining efforts; joining models" based on the discussion that Robbie started because he surveyed the development of open models/frameworks and asked why always new models/frameworks are developed though meanwhile there are a lot of them open available. It was discussed to start with a comparison of the models and especially find out which advantages and specialities every modeller/user of the models likes in the model/framework he/she uses. Maybe some advantages or even models can be merged in a follow up.
It could be one point for the strategy discussion if we want to push that. 
I post that already now so you have little time to reflect what you think about it.

**Comment by jnnr** [comment]
Concerning the overview of projects working with oeomof: 
I started collecting an up-to-date list of what is happening and what has happened regarding the projects done at RLI. Hope to get the responses that are still missing until our meeting to have a complete list by monday.

**Comment by jnnr** [comment]
I added a wiki page to collect the information on past and current projects involving oemof to have a background for the working group "Top1 oemof new projects and cooperations":

https://github.com/oemof/organisation/wiki/Developer-meeting-Dec.2017-Top-1:-Information-on-who-is-using-oemof-to-answer-which-questions

@simnh @ckaldemeyer @wolfbunke could you add the projects in Flensburg?

**Comment by wolfbunke** [comment]
Unfortunately, I cannot participate because I have a cold and hoarse. Best Wolf

**Comment by c-moeller** [comment]
We now have meeting minutes from our developer meeting:
https://github.com/oemof/organisation/wiki/Meeting-December-2017-Protocol

Some attendees might be missing. Please add them if you remember their full names :-)

And there are some gaps in "Workpackages and responsiblity". Please add if you remember (and comment here if you added somebody)

We definitely need a minute writer next time...
