### ISSUE TITLE
IMPORTANT: Organisation of the oemof developer group.

### ISSUE THREAD

**Issue by uvchik** [oemof/organisation#23]
The oemof organisation is divided in teams (see: https://github.com/orgs/oemof/teams). The purpose of each team is described in the team description.

Please read the following and decide in which team you want to be. You can write a comment with the team(s) you want to be a member in. **No answer** means that you do **not** want to be in **any team**. I will remove members who haven't answered next year.

Being a member of a team implies the following:

 * I will actively support the purpose of the team
 * I will answer to issues/pull requests regarding the team
 * I will answer if the team name is mentioned (@stupid_example_team_name)

If you do not want to do these things you can easily leave the team. Doing so will help the other team members to see on who they can rely.

We would like to have many members but it does not help if they do not participate.

Leaving a team is not for ever. You can make a break and join again after a while.

Sometimes we would like to have a consensus within a team and it is annoying if team members do not answer. "I will not have time the next two weeks, you can decide it without me." would be one acceptable answer for example.

**Comment by c-moeller** [comment]
demandlib, oemof-assistants, oemof developer group

**Comment by uvchik** [comment]
BTW It is easier to mange team members if you have an individual avatar. This does not have to be a picture of you but can also be something else (see: @gnn, @simnh, @ckaldemeyer for example).

**Comment by birgits** [comment]
demandlib, feedinlib, oemof developer group
Merci!

**Comment by ckaldemeyer** [comment]
Thanks!

**Comment by uvchik** [comment]
> Thanks!

@ckaldemeyer  Does "Thanks" mean you are fine with the groups you are in?

**Comment by jnnr** [comment]
I would like to join these teams: oemof-assistants, oemof-solph, please.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group 

At the developer meeting we decided that we want to be more responsive.

We also decided that I should remove everybody from the teams who did not answer to that call.

In that case there would be @birgits, @c-moeller, @jnnr and me left❗️ FOUR developers!

Please answer until 10th January...or just now.

**Comment by beritRLI** [comment]
I would like to join oemof developer group

**Comment by SabineHaas** [comment]
I would like to join the oemof developer group. Thanks!

**Comment by pkassing** [comment]
I would like to join oemof-tespy and oemof-assistants. Cheers

**Comment by mloenneberga** [comment]
oemof developer group. thanks!

**Comment by beritRLI** [comment]
I like to join also oemof_assistants and oep
Sorry, forgot that.

**Comment by uvchik** [comment]
What is the oep team for? Shouldn't we remove it?

As I understand it the oep is developed [here](https://github.com/openego/oeplatform). I would address the developers there and not here.

**Comment by beritRLI** [comment]
I agree to remove it here. We have to talk about where to move it if it can be continously developed out of open_eGo - but that is not a question of oemof

**Comment by simnh** [comment]
dev, solph, orga, core, outputlib

..for now...

**Comment by nesnoj** [comment]
oemof_assistants, thank you!

**Comment by henhuy** [comment]
oemof_outputlib, thank you!

**Comment by ckaldemeyer** [comment]
developer, outputlib, organisation, solph

**Comment by ckaldemeyer** [comment]
tespy

**Comment by ckaldemeyer** [comment]
And of course @fwitte for tespy

**Comment by uvchik** [comment]
he is the maintainer of this team

**Comment by gnn** [comment]
dev, solph, core, outputlib

Thanks @uvchik, for being so persistent.

**Comment by uvchik** [comment]
Thank you for your help.

Everybody who wants to support oemof can become a member of the oemof organisation. 

Just comment on issue #26 if you forgot to answer until now.
