### ISSUE TITLE
Absence from development process until September

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/organisation#27]
Hi everybody,

I will be absent from the development process (except for the next dev meeting and bugfixes on my way) until September since I want to focus on other things and have removed myself from all groups except "oemof developer group". This means that I will NOT read  and react on github messages except for the repository "organisation".

But my open PRs with @henhuy will be finished and I am always reacheable via e-mail, telephone and other channels ;-)

I think version 0.2 is a good milestone to be reached!

Cheers
Cord

**Comment by uvchik** [comment]
Sad, but thank you for your contribution to the v0.2 release and good luck with your other projects.

**Comment by ckaldemeyer** [comment]
> Sad, but thank you for your contribution to the v0.2 release and good luck with your other projects.

Thanks! ;-)
