### ISSUE TITLE
Dates for oemof Meeting Flensburg Fall 2018

### ISSUE THREAD

**Issue by simnh** [oemof/organisation#31]
Currently we are scheduling a date for the next meeting in Flensburg: 

https://dudle.inf.tu-dresden.de/Oemof_Meeting_Flensburg/

**Comment by simnh** [comment]
I think we can fix the dates **05.11 - 07.11.18**

**Comment by c-moeller** [comment]
The developer meeting is still far in the future, but it would be good if we already start to collect topics. For this purpose I created a wiki page: https://github.com/oemof/organisation/wiki/Meeting-November-2018

Please start to write topics you want to work on during the meeting to the agenda.

**Comment by ckaldemeyer** [comment]
@simnh : What about the venue? Can we use rooms withi VIL or do we have to book something else?

**Comment by simnh** [comment]
I think we can use rooms in VIL1, which should be enough for 15-18 people in one room. We have lots of room for break out groups!

**Comment by BastianSo** [comment]
@c-moeller : 
interested in following Topics: 

- Decision making process: **Additional Goal:** Understanding the perfect foresight and how can it be influenced?

- oemof models

- heat grids

- Analyzer

Further Topics:

Discussions about modelling topics
- Peer 2 Peer simulativ energy sharing. Goal: discuss possible control mechanisms
- Initial storage capacity. Goal: Decouple last and first timestep of the storage capacity #493
