### ISSUE TITLE
Revise front page of oemof website

### ISSUE THREAD

**Issue by c-moeller** [oemof/organisation#33]
On the last developer meeting we discussed a possible revision of the front page to emphasize more the uniqueness of oemof in the energy system modelling world (more community, less technical properties of the energy system modelling). Here is my proposal. See also the current front page as comparison. @oemof/oemof-developer-group @oemof/documentation What do you think? This is only a first draft, so comments are very welcome.

(I'm also in the middle of a revision process of the applications sub page and will open another issue the next days...)

**The possible new front page:**
![front_page_new](https://user-images.githubusercontent.com/8330132/43786685-87153b8a-9a69-11e8-9f01-82fafbd9ec01.png)

**The old one:**
![front_page](https://user-images.githubusercontent.com/8330132/43786697-95b6e044-9a69-11e8-8d04-968a582131ed.png)

**Comment by ckaldemeyer** [comment]
I would rather substitue "Versatile" in the old one with "Flexible and generic" of the new one and add some text for "community driven" in the old one. In any case, I would keep "Cross sectoral" as it is a key property compared to other model generators/frameworks.

Maybe a look into the currently released papers could offer some unique properties in comparison to other model generators/frameworks:

* https://www.sciencedirect.com/science/article/pii/S2211467X18300609
* https://link.springer.com/article/10.1186/s13705-018-0154-3

Thanks already for your effort!

**Comment by c-moeller** [comment]
Thanks for your comment! Sounds good. So maybe something like that?

> 
> Flexible and generic - Create applications and adapt components to your scope and purpose.
> Cross-Sectoral - Include and link the heat, power and mobility sector.
> Multiregional - Flexibly connect multiple regions.
> Time-step-flexible - Choose the temporal resolution mostly suited for your application.
> Modular - Choose from various python packages (libraries) with well defined interfaces for modelling and optimization.
> Open - Contribute to missing functions.
> Transparent - Find information you need to contribute in our documentation.
> Community driven - Participate in the development process.

I will also look into the papers after my holidays and will put it here again for discussion.

**Comment by jnnr** [comment]
Thanks for the improvements. However, what is missing at the moment is a link to the repository and readthedocs at the front page. If noone objects, I will take care of that.

**Comment by c-moeller** [comment]
Same here. Can we publish this? @oemof/oemof-website what do you think?
The draft for the new front page is now this:

![front_page_new_2](https://user-images.githubusercontent.com/8330132/48915441-f21bd380-ee7e-11e8-9383-0c08ad400f37.png)

**Comment by p-snft** [comment]
Thank you. I like the idea and the slightly adapted emphasis. There are a few points, I want to address to avoid misunderstandings and improve readability:

* *Time-step-flexible*: "Mostly" can be interpreted "most of the times" (like "almost", cf. "mostly positive" when weighting results of reviews), use "best suited".
* *Open*: (My linguistic intuition is picky here.) One cannot contribute to something that does not exist. Also, in the context of programming "function" has a very distinct meaning. Maybe, "Help to add missing features." would be better.
* *Transparent*: From the perspective of a potential new user not planning to contribute, this item would be more attractive without "to contribute". (As feedback is a form of contribution, some might contribute without being aware of it.)

**Comment by c-moeller** [comment]
Thanks for your feedback! I like your ideas. So the respective lines would look like this now:

Time-step-flexible - Choose the temporal resolution best suited for your application.
Open - Help to add missing features.
Transparent - Find information you need in our documentation.

**Comment by fwitte** [comment]
> Open - Help to add missing features.

I would suggest to write "new" instead of "missing", as "missing" implies that some features are known to be missing. "New" sounds positive while "missing" has some kind of negativity.

Have a nice weekend!

**Comment by c-moeller** [comment]
> I would suggest to write "new" instead of "missing"

Yeah, this is even better. I have adapted the draft according to your suggestions.

**Comment by p-snft** [comment]
Good idea, @fwitte. Tank you.

**Comment by c-moeller** [comment]
The frontpage has been updated now. Thank you all for your feedback!
