### ISSUE TITLE
2018 (November) Developer Meeting TODOs

### ISSUE THREAD

**Issue by gnn** [oemof/organisation#34]
This issue collects all the TODOs with which we came up during the developer meeting that took place in November 2018. This is just a general collection. Feel free to add anything that's missing. We'll create smaller issues for tasks which take longer to finish. Small hint: even if you're not the one who created this issue, you can try editing it. Some people can. ;)

  - [ ] Set up a contact form on the oemof website that uses [fire-bot](https://fire.fundersclub.com/) or the Github API to automatically create issues in the oemof repository. This lowers the participation barrier for people who can't be bothered to create a Github account.

  - [ ] Research alternatives to [reddit](https://reddit.com) or [discourse](https://www.discourse.org/). We do know that we want to move away from the openmod forum and we also know that we want a forum instead of  a mailing list because the former allows us to structure discussions better. The biggest problem currently is that the best solution has to be self hosted, which requires funding and maintenance time, while external solutions like [reddit](https://reddit.com) are always non-optimal in a certain way.

- [ ] Add major events in the history of oemof that should enter the timeline to this pad: https://ethercalc.org/q2q82eucgr34

- [ ] Update Website in terms of Names and Institutions. @simnh 

-  [ ] Collect names and Institutes @ckaldemeyer 

- [ ] Think about the community structure of oemof @simnh

- [ ] Finalize oemof timeline @jnnr 
 
 - [ ] Implement node removal in an energy system. This will be a rather "expensive" operation, as the `groups` will be reset and recreated. For convenience, bulk removal can be implemented, so that `group` recreation doesn't happen after every node is removed.

 - [ ] Implement mutable node attributes. There's one big caveat for this: it is impossible to intercept node attribute mutation for all scenarios. So while user's can mutate, they also have to explicitly notify the `EnergySystem` that they have done so, before rebuilding the optimization model.

- [ ]  create a heat component repository (sandbox)
  - structure: uwe makes a proposal

- [ ] Implement piecewise linear constraints. Applications: Decreasing investment costs, load-dependent efficiencies,... @jnnr 

- [ ] Create an example showing the possibilities of the ouputlib (views, slicing,..)

**Comment by FranziPl** [comment]
- [ ]  create a heat component repository (sandbox)
-structure: uwe makes a proposal

**Comment by henhuy** [comment]
Firebot is set up and ready to take issues!
Issues are created automatically by sending an email to:
 oemof@fire.fundersclub.com

Later on, this will be integrated in a form on oemof-webpage.
