### ISSUE TITLE
Oranisation Teams?

### ISSUE THREAD

**Issue by simnh** [oemof/organisation#39]
I just realized that we do not have teams in this repository. This however is sometimes diffucult if the decision process should be applied...

I think it would be good to have some like: website etc....

**Comment by uvchik** [comment]
The teams are organised at the top level, therefore we do have teams here. You could just add a team for the `website` or for `public relations`.

https://github.com/orgs/oemof/teams

**Comment by c-moeller** [comment]
I like the idea, especially for the website we should have a team.
@simnh which teams do you suggest. Will you add them?

**Comment by p-snft** [comment]
Yea, the website should have a team.

**Comment by simnh** [comment]
ok thanks!
