### ISSUE TITLE
A problematic book about oemof was published: 'Optimization of Energy Supply Systems' from Janet Nagel

### ISSUE THREAD

**Issue by uvchik** [oemof/organisation#40]
A book about oemof was published in the end of 2018.

In the beginning, the author asked me to make a review on this book. I started with the review but I stopped after a while due to the following reasons:

* I did not agree with the didactic structure (my opinion!)
   * in my opinion, the focus was too much on inner core functions, even developer do not need to understand (except core developer).
   * in my opinion, there was too much code copied into the book without further (enlightening) information.
   * in my opinion, it would be better to show a well formatted equation than the full code of the equation in reStructuredText (rst). We write the equations in rst to be interpreted by sphinx because we want the user to see a formatted equation.
  * in my opinion, there was too much code copied in the book without a proper explanation, that makes it easier to understand than just scrolling through the code on github.

* I found so much errors that it became very time-consuming.

It seems to me that the author does not know oemof very well, so I made the suggestion to work closer together with the community. In my opinion, a review was not the right way to improve the text, so I suggested a conceptional cooperation. The author declined that and went on on her own.

Most of the problems described above are still valid in the final version. Here are some...

* there are more than 7 pages explaining the groupings function, even though understanding the groupings is not needed to model with oemof.solph (and it is not explained correctly but reproduces the docstrings).
* there are more than 5 (confuse) pages on decorators, even though decorators are not needed to model with oemof.solph (I could continue this list)
* There is a lot of code/docstrings copied from the documentation or the code base (docstring) with the disadvantage that some bugs that are already fixed in the code are still in the book. Furthermore, the docstrings are not formatted (as they are in our documentation) but presented in source code.
* Reading the book I got the impression that the network classes are the base to create a solph model but solph user should use the solph classes as explained in our examples.
* The examples in the end of the book are just copied without further explanation.
* Some code examples are from oemof v0.1.0, some from oemof v0.2.0 but v0.3.0 will be released in spring, for example, with a revised Storage (which is already different to the one in the book).
* ....

We warned the author that the oemof project is in the beginning (3 years old, at the beginning of the book project) and will have a lot of changes.
We were open but had some doubts that a book might be the right media for such a changeable project. I tried to support the book in the beginning(!) even though I thought that improving the documentation would bring more support to the community (but maybe less credits to the author).

I come to my personal conclusion that the book is not up to date, does not have an 
additional value, has some errors and a structure that does not help to understand oemof.

@oemof/oemof-developer-group 
This is my very personal view on this issue but I think we should write an announcement, that this book does not have to do anything with us and that the documentation is the saver and more up to date source to learn about oemof.

**Comment by simnh** [comment]
I agree with @uvchik to write an announcement. I think this is very important as the book contains several errors, is already outdated and may lead people to investment money that is just not necessary (as we have docs) to invest. In addition, if people use this book as a lecture they will just learn wrong stuff. 

Besides this I think it's important to take it even one step further as it shows drawbacks of the current scientific environment where reputation is almost only based on number of publications. I think there is more to say in particular with regard to open source development by PhD's and other people supporting such projects without funding. Therefore, from a scientific perspective I would even argue that it is our **responsibility** to take a critical position on this and contribute to an ongoing discussion about the current scientific system.

**Comment by ckaldemeyer** [comment]
> I agree with @uvchik to write an announcement. I think this is very important as the book contains several errors, is already outdated and may lead people to investment money that is just not necessary (as we have docs) to invest. In addition, if people use this book as a lecture they will just learn wrong stuff.
> 
> Besides this I think it's important to take it even one step further as it shows drawbacks of the current scientific environment where reputation is almost only based on number of publications. I think there is more to say in particular with regard to open source development by PhD's and other people supporting such projects without funding. Therefore, from a scientific perspective I would even argue that it is our **responsibility** to take a critical position on this and contribute to an ongoing discussion about the current scientific system.

I go with both of you @uvchik and @simnh and think that we should clarify that (and why) we do not recommend the book.

@simnh: I see your criticism concerning the "publication culture" but maybe we can handle this in another (second) step separately to not mix things up and become personal in terms of the book question.

**Comment by p-snft** [comment]
Actually, I see the point in preferring *a* book over a purely digital documentation. This is not only about publication culture but it can also be more convenient to have some paper. Even if the documentation was perfect, some people would still prefer a book. In fact, some people will consider buying the book. If it is a bad source, there should be a warning. However, it should be clear that this warning is based on the content of the book and not on the author. Maybe it is wise to be diplomatic:

The existence of a book -- especially one that is not written by the programmers -- proves the relevance of the code. Unfortunately, there is outdated or inaccurate information in the book, so that we cannot unconditionally recommend it. Instead, interested users should consider the online documentation. We hope, there will be a revised version that can meet the expectations a reader would have in the book.

**Comment by fwitte** [comment]
I totally agree to the previous speakers! The main downside of a book on software at such a young stage is, that it will be (or is already) outdated quickly after publishing it. In my opinion, a book is better at giving an overview of different modeling approaches while referencing to the available software. Both, new and experienced users should always fall back on the software documentation. Documentation on new/modified/deprecated features, working examples etc. are always up to date!

**Comment by jnnr** [comment]
My opinion on the book:

I agree that a book can have an advantage in some situations. However, as @fwitte puts it, a book can in no way follow the development of a project in a young state that evolves quickly. One solution would be for such a book to operate on a more abstract level of understanding to give a broader picture.

But the book gets into a lot of details which is problematic in the way @uvchik wrote earlier. What is more, there are many mistakes. Therefore I think it is important that we give a statement that informs people:

* This is not our book,
* We distance ourselves from the book,
* We recommend using the documentation, which is run by the community and gives most detailed and up-to-date information on how to use and how to develop oemof.

**Comment by p-snft** [comment]
Some of the concerns named here are also addressed in the book:
* The book is about oemof v0.1 (made explicit in the preface).
* The author explicitly states, she is not part of the oemof community. ("this is a book about OEMOF and not a book by OEMOF, i.e., written by the OEMOF community")

However, some are other issues that the book does not tell the reader - they might indicate a lack of care.
* There are inconsistencies.
  * The text is in English but some abbreviations and the references are in German.
  * The coding style is rather bad.
* There are obvious mistakes (e.g. "Nonconvex functions have both an overall optimal level and several local optimal levels.").
* The scope is unclear. For example, there is an introduction to Python (including screenshots on how to install WinPython) but on the other hand some code examples (copied from GitHub) require fundamental knowledge of Python. Plus, the code snippets come first.
* Some content does not really add informations. (One might say, it just increases the page count.)

In total, I would not recommend the book. Still, I would not go so far to publicly expose the author. One of the assets of oemof is the welcoming community. Probably, a diplomatic warning is the best idea. To give you an idea what I mean, here is a draft:

> Recently, a book about oemof was released. We want to thank the author, Janet Nagel, for her effort. We feel that the existence of the book acknowledges the relevance of our code, especially as it is "a book about OEMOF and not a book by OEMOF, i.e., written by the OEMOF community" (as the author states it).

> The preface already states that it is hard to keep up with the development of the software. This is very true. So, unfortunately, there is a lot of outdated or inaccurate information in the book. This issue is addressed by the attempt to broaden the focus while sticking with the defined API and feature level of oemof 0.1. This wider focus is emphasized by the name of the book, which is "Optimization of Energy Supply Systems". It also briefly introduces e.g. Python and the theoretic foundations of oemof. Still, the book closely relates to the code and even cites larger excerpts. It is designed to be and understands itself as a book about oemof.

> Probably, the author was surprised by the amount of changes our young project goes through. Even if the text was up to date while writing, the publication process of the printed book in fact rendered part of the information unusable even before it became available. There has already been one API breaking release shortly after the book was written and a second one is currently in the pipeline. Especially, as mayor part of the book contains descriptions of the outdated API, we cannot recommend the book as a reference for oemof. Instead, interested users should consider the online documentation. We hope, there will be a revised version that can meet the expectations a reader would have in a book about oemof.

**Comment by uvchik** [comment]
> The book is about oemof v0.1 (made explicit in the preface).

The book is about v0.1.x in some parts and about v0.2.0 in others. Kind of confusing if you ask me. I also found the entity class which is not used since 0.0.10. I told her that the function is not used any more but she ignored it or just forgot it.

> Probably, the author was surprised by the amount of changes

We talked about this subject several times but she ignored our suggestions on that. In her opinion it is okay as it is.

> Some content does not really add informations. (One might say, it just increases the page count.)

This sounds euphemistic to me. I think it is hard to find more than 5 pages I would recommend to somebody else. Pages that have an additional value.

**Comment by p-snft** [comment]
I tried to be as polite as I can possibly be while at the same time stating that no one should buy that book. This approach, of course, brings some difficulties.

> The book is about v0.1.x in some parts and about v0.2.0 in others. Kind of confusing if you ask me. I also found the entity class which is not used since 0.0.10.

If it is a mixture of v0.0, v0.1 and v0.2, it is even worse. The preface said, it would be v0.1 and I believed it. 

>> Probably, the author was surprised by the amount of changes
>
> We talked about this subject several times but she ignored our suggestions on that.

Yes, this point is as far on the side of the author as I could possibly go. Still, even [these two guys](https://img.washingtonpost.com/rf/image_606w/2010-2019/WashingtonPost/2013/02/22/Editorial-Opinion/Graphics/toles02252013.jpg) will be surprised some day. If you feel, she "probably" knew better, it is still possible.

> I think it is hard to find more than 5 pages (...) that have an additional value.

I guess, my last point ("Some content does not really add informations.") was too vague to be understood. From my perspective, aggregating information is of value for itself. So just gathering information is fine, and even "adds information" (to the book). However, there are full sized screen shots showing where the bottom left corner of a Windows desktop is. I do not see the relevant information in that. (Well, I learned how the author's wallpaper looks like.)


When talking to people, I also like to directly address issues. This helps to solve problems. As far as I understand, you, @uvchik, already did so when corresponding with Janet. But now, we are not talking to her but are writing about her (and her work), so I suggested to adept content and style (maybe in the spirit of Hanlon's razor).

**Comment by SabineHaas** [comment]
Many important things have already been said - in my opinion the goal of our message should be:
* make users

**Comment by SabineHaas** [comment]
Many important things have already been said - in my opinion the goal of our message should be:

make sure users understand that:
* the documentation is the most recent and complete information they can get
* the book is not written by the oemof community

I think it might be wise to distance us from the book without even naming it. This could solve the problem of politeness vs. honesty. So I'd suggest to write a message at oemof.org and in the Documentation section of the readme saying:
*  the documentation is the most recent and complete information and we strongly recommend to read it
* there are publications on oemof.org
* any other material is not written by the oemof community and therefore we cannot guarantee its correctness 

This way we neither blame the author directly nor have to hide facts (of the book's mistakes) out of politeness.

**Comment by uvchik** [comment]
Thank you @p-snft. I know that personal feelings should not be part of such a statement and spoken with Hanlon's razor, we do not know the real reason...

But I disagree with @SabineHaas. I would name the book, because we are talking about this book. We are not talking about book projects in general. Even though the update-problem persists, it is possible to write a good book, but it might take some time and knowledge about the topic.

I think we can make some points clear and end with something positive. Everybody can help to make the documentation better....

-  This is not our book,
-  We distance ourselves from this book, because it does not meet our (quality?/scientific?/-?) standards
-  ~~We recommend using the documentation, which is run by the community and gives most detailed and up-to-date information on how to use and how to develop oemof.~~ (see below)
- The author seems to misunderstood  oemof in some ways because central sections contain wrong or misleading content
- We are aware that some errors in the book are copied from the documentation and we try hard to keep the documentation up to date with new features and to fix bugs. Therefore we highly recommend the documentation and want to encourage everybody to report problems.

**Comment by jnnr** [comment]
Thanks again to all of you for contributing your ideas and opinion. I really like your point, @p-snft, that we are not writing to the author but about her (or her book).

 I think it is a good idea to list the possible statements as @SabineHaas and @uvchik did. I agree with @uvchik that we should name the book, as we mean the book and do not mean any possible book about oemof.

-  ~~We distance ourselves from this book, because it does not meet our (quality?/scientific?/-?) standards~~
We distance ourselves from it because but we are not responsible for its scientific quality, measured by our standards or just the common ones.
- ~~The author seems to misunderstood  oemof in some ways because central sections contain wrong or misleading content~~
This is too much addressed to the person, in my view.
- ~~We are aware that some errors in the book are copied from the documentation and we try hard to keep the documentation up to date with new features and to fix bugs. Therefore we highly recommend the documentation and want to encourage everybody to report problems.~~
This is not the place for self-criticism: Of course there is a typo or mistake in the docu at some place or the other.

- Recently a book about oemof, 'Optimization of Energy Supply Systems' has been released.
- This book is not written by the oemof community
- We are not against books about software in general. In some instances, they give newcomers a comprehensive view of a field and the ways in which a software can be used to approach problems in that field. In this sense, they can fulfil a purpose that goes beyond what can be reached by the docs.
- However, we do not see this is the case with this book.
- Therefore, we distance ourselves from the book.
- We highly recommend consulting the docs, which is run by the community and kept up-to-date with the developing code. If there is anything missing or you have suggestions to improve the docs, you are welcome to

**Comment by p-snft** [comment]
- Actually, I like the criticism transported by self-criticism. It is a pretty subtle form
- According the wording: For me, "we distance ourselves" sonds pretty harsh.
- Even though the book is not good, there are positive aspects of the release. We should at least mention this.

**Comment by uvchik** [comment]
> Even though the book is not good, there are positive aspects of the release. We should at least mention this.

@p-snft : Really? What do you have in mind? I am really In do not see positive aspects.

> ~~The author seems to misunderstood  oemof in some ways because central sections contain wrong or misleading content~~
> This is too much addressed to the person, in my view.

@jnnr what about: Central paragraphs about oemof contain wrong or misleading content.

**Comment by p-snft** [comment]
> 
> 
> > Even though the book is not good, there are positive aspects of the release. We should at least mention this.
> 
> @p-snft : Really? What do you have in mind? I really do not see positive aspects.

At least for people with a traditional mindset, a book about something proves the relevance of that something. (This is true regardless of the quality of the book.) It's not much, but some persons at Springer thought oemof is important enough to release a book about it.

**Comment by ckaldemeyer** [comment]
@p-snft: I see and support your point that we are not writing to but about her. And I like the idea of the spirit of Hanlon's razor because we do not know her intentions.

> > > Even though the book is not good, there are positive aspects of the release. We should at least mention this.
> > 
> > 
> > @p-snft : Really? What do you have in mind? I really do not see positive aspects.
> 
> At least for people with a traditional mindset, a book about something proves the relevance of that something. (This is true regardless of the quality of the book.) It's not much, but some persons at Springer thought oemof is important enough to release a book about it.

I know of at least one case where Springer approaches people in a certain position (e.g. professors) and asks them to write some kind of book on an arbitrary topic. So again, we do not know what happened be hind the scenes.

To me, the criticism should be realized content-wise in a scientific manner as our community is located within this field and I feel that it is somehow our duty to reply on this obviously defective work.

What about this suggestion based on @jnnr and @uvchik:

- Recently a book about oemof, 'Optimization of Energy Supply Systems' has been released.
- This book is not written by the oemof community
- We are not against books about software in general. In some instances, they give newcomers a comprehensive view of a field and the ways in which a software can be used to approach problems in that field. In this sense, they can fulfil a purpose that goes beyond what can be reached by the docs.
- However, we do not see this is the case with this book and additionaly see that much of the information provided is outdated and not presented correctly.
- We therefore dissociate ourselves from the book as a primary source of information and recommend consulting the docs instead
- The documentation is run by the community and kept up-to-date with the developing code. If there is anything missing or you have suggestions to improve the docs, you are welcome to

**Comment by uvchik** [comment]
:+1:  @ckaldemeyer  Sounds like a good compromise to me.

**Comment by ckaldemeyer** [comment]
> +1 @ckaldemeyer Sounds like a good compromise to me.

@uvchik @p-snft I have added a last point from @SabineHaas so it should now also be in line with her feedback

**Comment by uvchik** [comment]
We could ask @SabineHaas about her opinion, but I would add the last sentences to the section where we publish presentations about oemof and not together with the book. But I am not against it.

The following presentations have not been reviewed and therefore we can not guarantee the correctness. They also may refer to older oemof versions.

**Comment by SabineHaas** [comment]
> We could ask @SabineHaas about her opinion, but I would add the last sentences to the section where we publish presentations about oemof and not together with the book. But I am not against it.

I am fine with the points you gathered and I think the last point "There are also other publications on oemof.org..." is not necessary anymore as we already distance ourselves from the book - that was just a subtle way of distancing us without naming the book.

**Comment by c-moeller** [comment]
We've created a proposal for the website text: https://etherpad.net/p/bRTUOLdiXT
@oemof-developer Please have a look and comment if you want to have something changed until end of next week (15.3.). I don't want to start a new discussion, so if there is something you want to change, please change the sentence/word directly in the text (and shortly state here what you have changed). Hope this procedure is ok for everybody! Thank you :slightly_smiling_face:

**Comment by c-moeller** [comment]
Thanks already for the changes. Sounds quite good now! Does anyone has a good idea for a news title? "Book about oemof published" might sound a bit weird in this context. I wrote an alternative to the pad, but feel free to comment on that, too.

And, if no one objects I will post the news this Friday.

**Comment by p-snft** [comment]
Let me comment on the options, we have so far:
1. "Criticism against oemof book": Rather harsh. Maybe, you will not read the text after the headline.
2. "Critique of oemof book": More elaborated than what we did.
3. "Skepticism about oemof book": More vague then the text but already sets the tone.
4. "oemof book published without community": Descriptive but implicitly transports criticism.
5. "Book about oemof published": Descriptive but implicitly transports consent.

I would prefer option 3 or 4. Headline 1 would fit to a dramatizing report about our reaction to the book, 2 would introduce the work of a literary critic, and 5 is almost advertising for those who do not read the text.

PS: Do we use American or British English?

**Comment by c-moeller** [comment]
I like number 3. Number 4 could also imply that we are offended about the fact that we are not part of the book/authorship.

**Comment by uvchik** [comment]
@p-snft  We once decided to use British English.

Number 3 is fine for me.

**Comment by p-snft** [comment]
> @p-snft We once decided to use British English.

It's "Scepticism about oemof book", then.

**Comment by jnnr** [comment]
I added a 6th option which avoids some of the shortcomings that were observed for the other options:

"Comment on recently published book about oemof"

No implicit critique or consent, no harshness. I prefer it to no. 3 because I do not understand what skepticism means in that context.

**Comment by p-snft** [comment]
Considering @c-moeller's comment, I do now also see the problems with 4. "Comment" would be fine for me, as well, maybe even better then 3.

**Comment by uvchik** [comment]
I agree also agree that "comment" is better.

I changed the title to make it clearer what this discussion is about. 

Shall we use the oemof account to publish the post to make clear that it is the output of a discussion process and not the statement of one person? Is anybody still afraid of legal consequences? In my opinion the actual statement is covered by the "freedom of expression".  In my opinion it is still a very polite statement and we can proof everything we wrote. It is no problem to find dozens of errors, misleading statements and outdated passages but it is hard to find any valuable information.

**Comment by c-moeller** [comment]
> Shall we use the oemof account to publish the post

Sounds good. Can anyone else post the message today? I'm sick at home and can't find the oemof account dates here.

**Comment by jnnr** [comment]
I can post it, though I would do it next week.

**Comment by jnnr** [comment]
The news was published on the oemof website
