### ISSUE TITLE
An anniversary paper to highlight the use/impact of oemof

### ISSUE THREAD

**Issue by gplssm** [oemof/organisation#47]
Dear oemofers,

The journal [Software Impacts](https://www.journals.elsevier.com/software-impacts/) offers to publish short articles that highlight the impact of FOSS software in research. Money quote

> Software Impacts provides a scholarly reference to software that has been used to address a research challenge. The journal disseminates impactful and re-usable scientific software through Original Software Publications (OSP) which describe the application of the software to research and the published outputs. 

In my opinion, this fits perfectly for oemof at its current state. It provides the opportunity to show where oemof is used in a citable manner.

An article includes the following

> A short descriptive paper of about three pages including an Impact Overview and references to publications where the software has been used

> An open source software distribution with support material.

What do you think about a joint publication among @oemof-developer?

**Comment by ckaldemeyer** [comment]
I really like the idea! As I am still busy with my thesis and another paper, I would offer to "review" the paper and add only a couple of paragraphs if/where needed.

**Comment by p-snft** [comment]
Indeed, this sounds very much fitting. I would join the writing team if we decide to publish such a paper.

**Comment by simnh** [comment]
I like the idea and would contribute to the paper. I can also offer do coordinate but I do not have to (if you are,  @gplssm, or anyone else is keen to do this)

**Comment by jnnr** [comment]
Sounds like a good idea. I would rather not do the coordination, but I would definitely join the writing team.

**Comment by gplssm** [comment]
Thanks for the replies @ckaldemeyer @p-snft @simnh @jnnr. In addition, @uvchik told me he would join this publication as well.
I'm happy to hear that you like the idea!

I'm even more happy that @simnh offered to coordinate! Me personally, I would just like to see this paper being published. I don't  want to be the lead author, maybe I can support the paper by writing some sentences...

I would like the idea to have the paper submitted until oemof's 5th birthday (dev meeting at Beuth in  December). This would imply that the writing process must be started soonish.

Four points to decide on soon:

- Find the lead author (who is taking over coordination)
- Find funding for the [article processing fee](https://www.elsevier.com/journals/software-impacts/2665-9638/open-access-journal) of 250 €
- Finalize list of contributing authors
- Agree on a planned submission date

In order to find the lead author, I would ask again for people who are interested to take this role. Please :hand: 
**Deadline:** 22th of September 12 am.

**Comment by simnh** [comment]
>     1. Lead author: In my opinion, it would be just to give the lead to an experienced oemof developer. @simnh (joined 2016) would be a good option. If, for some reason, you want some choice, I would not object - despite the fact that I don't feel to be the best candidate.

Would be fine for me, I also have the time to do it. Maybe @gplssm has an opinion on that, because we already had paper in this kind of a constellation ;-) 
> 
>     2. I have the experience, that the fees are covered by the institute of the primary author. At least, it has been like this for my past publications.

I could also apply at our 'research support fund' for such a paper. This should not be any problem. 
> 
>     3. We have six persons who pledged their support - that should be enough, we could just assign tasks. I would not exclude additional persons from contributing. Anyhow, we have to name all significant contributors to the paper (and only those).

Sounds good to me!  

> 
>     4. December sounds fine for me. However, we should check how much time we should reserve for internal publication rules of the institutes. For example, I am advised to notify my head of institute one week in advance - including the text to be submitted, but I know from others who have more time-consuming internal processes.

For me sounds fine, and I do not have any restrictions except the time for doing it 


I could offer our overleaf account for collaborative writing (TeX I assume!).

**Comment by p-snft** [comment]
Overleaf would be magnificent. :)

**Comment by uvchik** [comment]
I really would like to help to coordinate the paper. After submitting my PhD I will have some extra time.

We have to clarify, whether we want to write about oemof or solph. I personally would like to write about oemof but it might be to broad in the sense of the journal. What do you think?

**Comment by uvchik** [comment]
Shall we open a chat to make the communication a bit easier/faster (e.g. telegram, signal)?

**Comment by simnh** [comment]
Ok, so I could start a project and invite everyone who is interested.

**Comment by p-snft** [comment]
Group: I'd prefer signal, but most of you seem to use Telegram.

Overleaf: Go for it.

I am really looking forward to start.

**Comment by uvchik** [comment]
Further discussions will take place in the chat channel. If you still want to take part please let me know soon.

**Comment by gplssm** [comment]
The group of authors are working on it. So, I close the issue
