### ISSUE TITLE
Contribution to openmod Berlin (January 2020)

### ISSUE THREAD

**Issue by jnnr** [oemof/organisation#48]
In the issue on the next dev meeting in December #46, some of us have shown their interest in contributing something from the oemof side to the openmod meeting. I think it is nice to use the coincidence of having both meeting at roughly the same place and time. I open the issue so we can discuss ideas.

First idea: There is a group of researchers called "Python Wärme" at TU Berlin that have regular meetings to talk about thermal system modeling in python. @jakob-wo has been there and presented already. We could aim for a common session on that topic where we present our tools, challegenges, etc. What do you think, @oemof-developer?

**Comment by mloenneberga** [comment]
It has just been published that the next OpenMod workshop will be postponed to 15-17.1.2020. It would be still great to contribute with a hand-on tutorial, etc. but it won't happen in the week of the developer meeting. Shall we close this issue?

**Comment by p-snft** [comment]
Changing the title should be enough - there can still be an oemof contribution.

**Comment by jnnr** [comment]
There was a oemof contribution, namely on tespy. Good session! The meeting is over, so I close the issue.
