### ISSUE TITLE
Introduce a new repository for district heating system models

### ISSUE THREAD

**Issue by jnnr** [oemof/organisation#51]
I have been talking to several oemof developers and have learned that a couple of us are working on district heating networks. We already discussed the topic at earlier dev meetings, recently at a conference in Copenhagen and on github.

On github, there is the issue https://github.com/oemof/oemof/issues/618 and the PR https://github.com/oemof/oemof/pull/619 of @joroeder , which proposes and implements a new component for district heating pipes. Also, recently @joroeder  showed this example of a district heating optimisation, which builds a district heating system from input files: https://github.com/quarree100/dhs_optimization

Modeling district heating systems goes beyond a single component. There is a lot of detail in describing the topology and properties of the district heating network as well as in the specific problem setting one aims to answer with the model. These details arise wether you try to build the optimisation models using solph, simulation models using tespy or any other approach. A structured package could help building such models and also coupling them.

Therefore, I would like to introduce a new repository for district heating systems which we can develop together. I imagine the package to provide these functionalities:

* Defined data format,
* Importers/exporters from/to
    * geodataframe
    * graphml
    * shapefile
    * ...
* Import from osm,
* Defined problem definition of district heating optimisation and simulation,
* Model builders that create a solph/tespy model,
* Consistency checks,
* Postprocessing functions, derived metrics,
* Possibly other nice functions like network aggregation,
* Plots/Maps,
* Examples,
* Tests.

As I mentioned, there are already a couple of efforts to address district heating.  To combine these, it makes sense to join them in a meaningful way. Therefore, it makes sense to have a common repository under oemof. Given the sustained interest in the topic of district heating,  I assume that such a package would be worth to start and also there would be some interest to maintain it.

One could argue that oemof-thermal would be the right place to put it. However, the functionality described above is a bit different to the other thermal energy components. With the advice in mind that repos should represent entities with a well-defined scope and purpose, I would rather do this on a separate one.

I have set up a repo and developed a first structure that we could use to build the package described above. At the moment, it is under the oemof-heat organisation: https://github.com/oemof-heat/DHNx. 

* module structure
* a central network object
* importer structure
* a structure to build different models (simulation/operational optimisation/investment optimisation)
* classes for plots
* tests
* CI
* examples
    * osm import
    * plots

If you like the idea and agree, we could move it to oemof and develop it together.

In addition to this, we got some validation data we will be able to publish under an open license, which could serve as a benchmark. 

@c-moeller, @FranziPl, @jakob-wo would support the initiative.

I reserved a session on district heating system models on the next dev meeting (Wed, 15.30), where we can discuss and work on the topic together.

What do you think?

@oemof/oemof-heat 
@oemof-developer

**Comment by joroeder** [comment]
Thanks for this issue, I think that's a good idea. Let's discuss at the dev meeting how to continue ...

**Comment by joroeder** [comment]
I think there was nothing against such a repo. Hey, how shall we proceed? Put everythink we have in a new repo and than start to structure?
We need a name, how about simply "oemof-dhs", dhs for district heating systems

**Comment by jnnr** [comment]
Hi @joroeder, thanks for asking! Let's proceed as we concluded at the dev-meeting in December. I promised I would clean up of the basic structure of the existing repo in our project (https://github.com/oemof-heat/DHNx) according to the sketch that I showed. When I am ready with this, I would like to move the repo to oemof, so we can start to integrate the different parts. 

Today and this week I am working on the cleaner structure, so I hope it will be ready by next week. If you want to have a look in advance to get an impression, check out the repo and especially this PR: https://github.com/oemof-heat/DHNx/pull/21

If you like, you can give some feedback already, but I promise to improve accessibility in the next days.

I started calling it DHNx, alluding to the networkx package. But I realized that a name that is easily pronounced is a good feature. So let's discuss about a good name (now or later). To avoid getting stopped by that, we can take anything as a working name and make a final decision before the first release.

**Comment by jnnr** [comment]
Update: I did not finish all steps for the move last week. This week will work out.

**Comment by jnnr** [comment]
I moved the repo to oemof. I assume that the further discussion will take place in issues on the repo, so I close this one here.
