### ISSUE TITLE
Addressing energy system modeling challenges, the example of oemof

### ISSUE THREAD

**Issue by fraukewiese** [oemof/organisation#7]
result of phone call with @gplessm: He will join for writing. Together with @simnh we talk on the phone on friday 11 o'clock (not the webco room because I will not have internet then)
+496151627315124
PIN 7041
Draft/Contents still here: https://www.overleaf.com/5254475wxgygx#/16524521/
We would like to use an open access journal, energy-related, not too expensive, if you have any ideas, we are happy to hear about that.

**Comment by beritRLI** [comment]
we wrote already things to some of the points that we now skip from our paper. Do you have access to the git folder where it is stored? if not ask Eva for access.

**Comment by gplssm** [comment]
I assume it's located in the openego-sftp, but I can't find it...

If you like to provide this content, it would be helpful to say which parts you've already wrote that you kicked out of the paper.

**Comment by fraukewiese** [comment]
Which journal?
International Journal of Sustainable Energy Planing and Management
https://journals.aau.dk/index.php/sepm/about/submissions#authorGuidelines
pro: open access / no fee / peer-review / 5000-8000
contra: latex style / bad experience from Marion

Energy Strategy Reviews
http://www.journals.elsevier.com/energy-strategy-reviews
pro: fits thematically / Mark Howell (osemosys as author) / experience from Uwe
contra: USD 2500 publication fee for open access / not fully open access

Energy Reports
http://www.journals.elsevier.com/energy-reports/
Direct submissions to the journal can be on any aspect of energy research, either from a technical engineering viewpoint or from a social research aspect. All Energy subject areas will be considered (e.g. renewables, fossil, nuclear). Article length is limited to 4000 words (not including references) with normally no more than 5 figures and 3 tables (table and figures legends are not included in the aforementioned word limit). Energy Reports operates a single blind peer review and generally allows for only one revision iteration.
pro: fully open access / fast
contra: USD 1125 / eventually not perfectly fitting thematically?

Energy, Sustainability and Society
http://energsustainsoc.springeropen.com/about

PLOS ONE
http://journals.plos.org/plosone/s/journal-information
PLOS ONE features reports of original research from all disciplines within science and medicine. By not excluding research on the basis of subject area, PLOS ONE facilitates the discovery of connections between research whether within or between disciplines.
Submissions describing methods, software, databases, or other tools 	We consider submissions describing methods, software, databases, or other tools if they follow the appropriate reporting guidelines. See the submission guidelines for more information.
pro: one of the very first open access / fully open access / latex / good policies
contra: $1,495 USD (http://journals.plos.org/plosone/s/publication-fees) / not energy-realated

**Comment by fraukewiese** [comment]
Overview / database of open access journals:
https://doaj.org/

**Comment by gplssm** [comment]
I can't get a connection to +496151627315124 is it the right number?

**Comment by simnh** [comment]
After our telephone conference on firday I will briefly give a update here: 

* We will write a paper with all oemof developers that are interested in participating
* @uvchik and I will finalize the structure and be responsible for the process and organisation etc. 
* Everyone who wants to join is welcome (but writing a part of the is obligatory)
* We want to publish open-access 
* Further discussions about this paper will take place in individual web-conferences or meetings

So far we are 5 interested people: @fraukewiese @uvchik @ckaldemeyer @gplssm and me. 

Tell us if you are interested and we will keep you updated!

**Comment by caro-rli** [comment]
Thank you for the update and information. I would be happy to join if I feel I can contribute in a useful way. So I'm looking forward to the paper outline and further updates. Thanks!

**Comment by fraukewiese** [comment]
**WHICH PAPER?**
suggestion by @gplssm  and @fraukewiese to @simnh @caro-rli @uvchik  :
International Journal of Sustainable Energy Planing and Management
https://journals.aau.dk/index.php/sepm/about/submissions#authorGuidelines

Although Simon could offer some research money for publishing fees, we think this journal has a good open policy, the quality is good (peer review) and the scope fits quite well. Drawbacks are a long review time (according to Marion) and officially no latex-possibility (but was possible for Marion on request). And although it is a Creative Commons License, there are some restrictions:
_Articles published in International Journal of Sustainable Energy Planning and Management are following the license Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0)
Authors retain copyright and grant the journal right of first publication with the work simultaneously licensed under a Creative Commons Attribution License: Attribution - NonCommercial - NoDerivs (by-nc-nd). Further information about Creative Commons_
_Authors can archive post-print (final draft post-refereering) on personal websites or institutional repositories under these conditions:
-     Publishers version cannot be stored elsewhere but on publishers homepage
-     Published source must be acknowledged
-     Must link to publisher version_

**Summary:**
License: CC BY-NC-ND 3.0)
Fee: None
Quality: Peer-review yeas
VIsibility:  approved by the Norwegian bibliometric Kanalregister, Danish counterpart BFI, registered/indexed in Ulrichs Web, Directory of Open-Access Journals, Sherpa/Romeo, DataCite and is under evaluation by Scopus.
Article length: 5000-8000 words including everything
Format: no latex but high probability that this is possible on demand

**Comment by simnh** [comment]
I think we should check for latex first. Please, please, don not less us write a paper with libreoffice or -even worse - word...

**Comment by simnh** [comment]
ah, and thanks for checking!

**Comment by fraukewiese** [comment]
as soon as there is the title and 3 sentences of the content, we can send them a mail to make sure latex is possible. word or libreoffice would be a no go I guess.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
:+1:
